language: csharp
solution: EnigmaBinary.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore EnigmaBinary.sln
after_script:
  - nunit-console EnigmaBinaryTest/bin/Debug/EnigmaBinaryTest.dll